WITH FIRST_GEN AS (SELECT ID FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
     ),
     SECOND_GEN AS (SELECT A.ID, A.PARENT_ID FROM ECOLI_DATA A
               JOIN FIRST_GEN B ON A.PARENT_ID = B.ID)

SELECT A.ID FROM ECOLI_DATA A
JOIN SECOND_GEN B ON A.PARENT_ID = B.ID